# Generated by Django 6.0.3 on 2026-03-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isbn',
            new_name='asin',
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
