# Generated by Django 6.0.3 on 2026-03-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_author_slug_alter_book_slug_alter_genere_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='asin',
            new_name='isbn',
        ),
    ]
